### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by pergrand** [championheng/ip-proxy-pools-regularly#1]
存放Redis时 先删除库是不是不太好，假如爬虫正在取ip；可以使用set并 先对Redis的ip检测把失效的ip移除。没仔细看代码，只少做了修改实现了功能。另外还想请教个爬虫的问题，有没有轮询取ip进行爬虫，当ip失效时继续取，每个ip爬取一个小时，换ip。。。找了一些没有很好的实现

**Comment by dhengyi** [comment]
谢谢你的提问。我记得当时在博客中有写到存放Redis时先进行删库是一种很愚蠢的做法，因为是重构第二版，所以有很多东西还是没有考虑到。目前我正在进行第三版的优化，准备给xici代理上抓取下来的IP添加一个使用计数器，如果连续三次从这个IP代理池中取出来的IP不可用，我就将它删除掉，否则就将它留下来。原因是我在使用xici代理的IP之后发现大部分IP都是一会可用，一会不可用，因此准备做出这个优化。至于轮询取IP我在第一版IP代理池中使用的这种方法，但是觉得这种方法使用起来有点差强人意，因此我在重构中使用了产生随机数的方法。至于整个IP代理池什么时候用，我觉得你可以将这个东西放到一个后台线程中去运行，并且要随时关注其中的数量，如果一旦IP代理池中的IP数量低于一个阈值，就应该通知所有工作的线程进行阻塞然后让IP代理池重新抓取新的IP。

在 2018年1月22日 下午5:24，pergrand <notifications@github.com>写道：

**Comment by pergrand** [comment]
我现在的做法是 每十分钟去redis随机取一个ip，不可用删掉，继续取，如果redis没有ip的，目前我的做法是取不到ip时用个默认的，都是基于你的代码稍加修改的，谢谢你后面的思路，我刚开始想那样实现，但是时间有点紧。问个问题，你爬取4000条 xici会封ip吗，我上次自己写的爬虫，以为没问题，3000就封了，我现在准备6个小时去爬取一次xici，应该没问题吧

**Comment by pergrand** [comment]
一般 这个ip很快就不能用了，所以爬取xici频率要提高一些，能不能使用已经爬取的ip作为代理ip爬xici，我之前试过，也是基本不能用。

**Comment by championheng** [comment]
啊哈？

**Comment by dhengyi** [comment]
不好意思，现在才给你回复，我是即抓即用，而且是一个有解析网页的请求就在数据库中抓取新的ip，我目前给ip加上了使用计数器，如果同样的ip连续三次不能使用，就将其抛弃，否则将其计数器置0。然后我就是将之前爬取的ip直接拿来进行新的网页抓取，20个线程，大概15分钟左右抓了4000个IP，最后过滤下来，给数据库中可以存储2000多个。

**Comment by pergrand** [comment]
这个邮箱很少看，突然看到你的信息；我春节前已经解决了，至今一直再爬数据。在你的基础上稍微修改了，1.我现在使用的redis的set存放ip(不用考虑ip重复)；2. IP来源我使用的https://github.com/fate0/proxylist/blob/master/proxy.list （每15分钟会更新一次ip） 西刺的有效ip太少了；3.我每小时会更新一下redis的ip 先删除无效ip，再检查redis中的ip少于40个时才会更新ip库。4.在使用ip时，我是每十分钟去库里取ip，如果ip无效继续取ip。



alilzg@aliyun.com
 
发件人： spider_hgyi
发送时间： 2018-02-01 19:30
收件人： championheng/ip-proxy-pools-regularly
抄送： pergrand; State change
主题： Re: [championheng/ip-proxy-pools-regularly] 一些疑问 (#1)
不好意思，现在才给你回复，我是即抓即用，而且是一个有解析网页的请求就在数据库中抓取新的ip，我目前给ip加上了使用计数器，如果同样的ip连续三次不能使用，就将其抛弃，否则将其计数器置0。然后我就是将之前爬取的ip直接拿来进行新的网页抓取，20个线程，大概15分钟左右抓了4000个IP，最后过滤下来，给数据库中可以存储2000多个。
